### ISSUE TITLE
`marker-placement-keyword` CartoCSS property with multi-geometries?

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#418]
A comment by @ztephm , that I need some clarification about.  

http://docs.cartodb.com/cartodb-editor.html#marker-placement-keyword
How does this work with SQL? Meaning how do the point(s) know to plot along a line? I am only asking since the Editor cannot have points and lines in the same layer. 

@rochoa @fdansv , please advise so that we can ensure the description is correct and makes sense.  Also, so that we can add more value to the description about what happens when using SQL.

**Comment by ztephm** [comment]
Hi, to clarify I was looking at:
"Note: If placing markers on a line, markers appear multiple times along a line. You can apply 'interior' to ensure correct placement on a line. Points placed on polygons are forced to be inside the polygon interior."

I wasn't sure how markers are "placed on a line" since only one type of geometry is allowed per layer in the Editor. 

Does our system automatically calculate an invisible line between marker locations? Or is this used if user is applying their own SQL query, something like ST_DumpPoints to get points from a line?

**Comment by csobier** [comment]
As per my conversation with @saleiva , I am reassigning all open CartoCSS issues that need rochoa's input to a later milestone, as they have a high-priority deliverable that needs his attention.

**Comment by rochoa** [comment]
Check this: https://github.com/CartoDB/mapnik-reference/blob/a9a4536116aa8b3e1fe6433b2c8da25321dc7f7d/2.3.0/reference.json#L746-L756

BTW, the editor might not support multiple geometries but we potentially support it (I say potentially because I'm not fully aware of all cases).

About how the transformation works: mapnik can change the way it renders a geometry based on the styling. So it can end drawing a Line as points if the styling is for points. So if there is no specific CartoCSS to cover both types of geometries it will try to do its best to render with the provided style.

So having a lines datasets with points style, it will render points, and depending on the `marker-placement` it will render all points (`marker-placement: point;`) or just one point per geometry (`marker-placement: line or interior;`):

```css
/** simple visualization */
#untitled_table_19{
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 1;
  marker-line-opacity: 1;
  marker-placement: point;
  marker-type: ellipse;
  marker-width: 10;
  marker-fill: #FF6600;
  marker-allow-overlap: true;
}
```
